version: '3'

networks:
  burn-secret_frontend:
    external: true

services:
  app:
    build: .
    user: "node"
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    networks:
      - burn-secret_frontend
